version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dev.Dockerfile
    deploy:
      replicas: 1
    hostname: backend
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=prae
      - DB_PASSWORD=password
      - DB_NAME=prae
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - KINDE_CLIENT_ID=youridhere
      - KINDE_CLIENT_SECRET=yoursecrethere
      - KINDE_HOST=https://your.prefix.kinde.com
      - KINDE_REDIRECT_URL=http://127.0.0.1:80/api/v1/kinde/callback
      - KINDE_AUDIENCE_API=127.0.0.1
      - GRANT_TYPE=AUTHORIZATION_CODE
    volumes:
      - ./backend:/opt/prae-be

  postgres:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=prae
      - POSTGRES_USER=prae
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  redis:
    image: redis
    hostname: redis
    ulimits:
      memlock: -1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dev.Dockerfile
    deploy:
      replicas: 1
    hostname: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - ./frontend/src:/opt/prae-fe/src

  ingress:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    links:
      - backend
      - frontend
  
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
