version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    hostname: backend
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    environment:
      - DB_DRIVER=sqlite
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - KINDE_CLIENT_ID=1aad3dd1cffc4b43b3cfe0fdad018a51
      - KINDE_CLIENT_SECRET=6Eao5VoN1AapWltB8bhrxAQwMES70ZatxWWBI6No3W5o6aOjO
      - KINDE_HOST=https://hyscript7-praedev.eu.kinde.com
      - KINDE_REDIRECT_URL=http://127.0.0.1:8000/api/v1/kinde/callback
      - KINDE_AUDIENCE_API=127.0.0.1
      - GRANT_TYPE=AUTHORIZATION_CODE

  postgres:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=prae
      - POSTGRES_USER=prae
      - POSTGRES_PASSWORD=password

  redis:
    image: redis
    hostname: redis
    ulimits:
      memlock: -1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    hostname: frontend
    depends_on:
      - backend
    links:
      - backend

  ingress:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    links:
      - backend
      - frontend
